### ISSUE TITLE
Using console as an api

### ISSUE THREAD

**Issue by cblavier** [bcoe/sandcastle#54]
Hey, I can't manage to expose console as an API (function is properly exposed, but nothing is printed to stdout)

Here is my `api.js` 
```
exports.api = {
  console: console
};
```

And my code
```
var SandCastle = require('sandcastle').SandCastle;

var sandcastle = new SandCastle({
  api: './api.js'
});

var script = sandcastle.createScript("\
  exports.main = function() {\
    console.log('hello!');\
    exit();\
  }\
");

script.on('exit', function(err, output) {
  process.exit(0);
});

script.run();
```

Any help would be much appreciated :)

**Comment by thedjpetersen** [comment]
trying running your script with the DEBUG environment variable set to sandcastle - 

ala `DEBUG=sandcastle, node myscript.js`

**Comment by cblavier** [comment]
Working fine :) Thanks!
