### ISSUE TITLE
Build: error

### ISSUE THREAD

**Issue by cmdelatorre** [bcoe/sandcastle#56]
The https://travis-ci.org/bcoe/sandcastle is reporting: error, but I don't know whats failing. Can you update on the current status of this project?

I'd like to use it in a production environment.

**Comment by bcoe** [comment]
Hey @cmdelatorre sorry for the slow reply, I was on vacation. The build is fixed now:

https://github.com/bcoe/sandcastle/pull/57

**Comment by cmdelatorre** [comment]
Awesome, thanks!
