### ISSUE TITLE
Node v4.1.0 - Buffer.indexOf Warning

### ISSUE THREAD

**Issue by benjsicam** [bcoe/sandcastle#60]
Using Node.js v4.1.0, I am getting this warning message:

```
Warning: using slow naiv Buffer.indexOf function!
`npm install buffertools` to speed things up.
```

Seems to be coming from the bufferstream dependency.

**Comment by bcoe** [comment]
`bufferstream` uses the compiled `buffertools` dependency, but if it can't compile on the given platform it falls back to `bufferjs` -- this warning message is certainly ugly, but I think it's the correct behavior. Once `node-gyp` is doing the right thing on the `LTS` release of Node.js, I think you'll find that this problem goes away.
